# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'UI/getBarcode.ui'
# Created by: PyQt5 UI code generator 5.15.7
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import time

class checkPoint_Window(QMainWindow):
    '''The Window Class'''
    def setupUi(self, Window, WINDOW_WIDTH = 900, WINDOW_HEIGHT = 600, GATE_TYPE = ""):
        '''Construct window components'''

        BUTTON_WIDTH = 100
        BUTTON_HEIGHT = 36
        GIF_WIDTH = 100
        GIF_HEIGHT = 100
        self.gate_type = GATE_TYPE
        self.row = 0
        font = QFont()

        # create components
        Window.resize(WINDOW_WIDTH, WINDOW_HEIGHT)
        self.centralwidget = QWidget(Window)

        self.Window_label = QLabel(self.centralwidget)
        self.Window_label.setGeometry(QRect(0, 0, WINDOW_WIDTH, 40))
        self.Window_label.setAlignment(Qt.AlignCenter)
        self.Window_label.setStyleSheet("QFrame" 
                                        "{"
                                            "font-size: 34px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                        "}"
                                        )

        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QRect(40, 100, WINDOW_WIDTH-80, int(WINDOW_HEIGHT/1.75)))
        self.scrollAreaWidgetContents = QWidget()
        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.scrollArea.setWidgetResizable(True)

        self.frame = QFrame(self.centralwidget)
        self.frame.setGeometry(QRect(40, 45, WINDOW_WIDTH-80, 45))
        self.frame.setStyleSheet("QFrame" 
                                    "{"
                                        "background-color: rgb(230,230,230);"
                                        "border-style: outset;"
                                        "border-width: 0.5px;"
                                        "border-radius: 4px;"
                                        "border-color: white;"
                                        "padding: 1px;"
                                    "}"
                                    )
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)

        self.num_label = QLabel(self.frame)
        self.num_label.setGeometry(QRect(30, 3, 50, 40))
        self.num_label.setStyleSheet("QFrame" 
                                    "{"
                                        "background-color: rgb(235,235,235);"
                                        "border-style: outset;"
                                        "border-width: 0.5;"
                                        "border-radius: 2;"
                                        "border-color: rgb(200,200,200);"
                                        "font-size: 24px;"
                                        "font-family: Times New Roman;"    
                                        "font-weight: bold;"
                                        "color: black;"
                                        "padding: 1px;"
                                    "}"
                                    )
        self.num_label.setAlignment(Qt.AlignCenter)
        self.num_label.setFont(font)
        
        self.key_label = QLabel(self.frame)
        self.key_label.setGeometry(QRect(145, 3, int(WINDOW_WIDTH/2)+200, 40))
        self.key_label.setStyleSheet("QFrame" 
                                        "{"
                                            "background-color: rgb(235,235,235);"
                                            "border-style: outset;"
                                            "border-width: 0.5px;"
                                            "border-radius: 4px;"
                                            "border-color: rgb(200,200,200);"
                                            "font-size: 24px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )
        self.key_label.setAlignment(Qt.AlignCenter)
        self.key_label.setFont(font)

        self.logs_box = QTextEdit(self.centralwidget)
        self.logs_box.setGeometry(QRect(150, int(1.55*WINDOW_HEIGHT/2), 
                                        int(WINDOW_WIDTH-(BUTTON_WIDTH)*4.25), int(4.3*WINDOW_HEIGHT/24)))

        self.logs_label = QLabel(self.centralwidget)
        self.logs_label.setGeometry(QRect(80, int(1.5*WINDOW_HEIGHT/2), 
                                        WINDOW_WIDTH-(BUTTON_WIDTH)*2, int(3.5*WINDOW_HEIGHT/24)))
        self.logs_label.setStyleSheet("QFrame" 
                                        "{"
                                            "font-size: 24px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )

        self.clearLogs_btn = QPushButton("Clear Logs", self.centralwidget)
        self.clearLogs_btn.setGeometry(QRect(40, int(1.5*WINDOW_HEIGHT/2)+85, 
                                        BUTTON_WIDTH, BUTTON_HEIGHT))
        self.clearLogs_btn.setStyleSheet("QPushButton" 
                                        "{"
                                            "background-color: rgb(200,200,200);"
                                            "border-style: outset;"
                                            "border-width: 2px;"
                                            "border-radius: 6px;"
                                            "border-color: grey;"
                                            "font-size: 18px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        "QPushButton::pressed" 
                                        "{"
                                            "background-color: rgb(150, 150, 150);"
                                            "border-style: inset;"
                                        "}"
                                        )

        self.gate_statusLabel = QLabel("Gate Status", self.centralwidget)
        self.gate_statusLabel.setAlignment(Qt.AlignCenter)
        self.gate_statusLabel.setStyleSheet("QFrame" 
                                        "{"
                                            "font-size: 16px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )
        self.gate_statusLabel.setGeometry(QRect(int(WINDOW_WIDTH-(GIF_WIDTH*2.5)), int(1.475*WINDOW_HEIGHT/2), 
                                            BUTTON_WIDTH, BUTTON_HEIGHT))

        self.gate_statusBox = QGroupBox(self.centralwidget)
        self.gate_statusBox.setStyleSheet("QFrame" 
                                        "{"
                                            "font-size: 24px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )
        self.gate_statusBox.setGeometry(QRect(int(WINDOW_WIDTH-(GIF_WIDTH*2.5)), int(1.575*WINDOW_HEIGHT/2), 
                                            GIF_WIDTH, GIF_HEIGHT))

        self.gate_statusText = QLabel("-----", self.gate_statusBox)
        self.gate_statusText.setAlignment(Qt.AlignCenter)
        self.gate_statusText.setGeometry(QRect(0, 0, GIF_WIDTH, GIF_HEIGHT))

        self.request_statusLabel = QLabel("Post Status", self.centralwidget)
        self.request_statusLabel.setAlignment(Qt.AlignCenter)
        self.request_statusLabel.setStyleSheet("QFrame" 
                                        "{"
                                            "font-size: 16px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )
        self.request_statusLabel.setGeometry(QRect(WINDOW_WIDTH-GIF_WIDTH-40, int(1.475*WINDOW_HEIGHT/2), 
                                            BUTTON_WIDTH, BUTTON_HEIGHT))

        self.request_statusBox = QGroupBox(self.centralwidget)
        self.request_statusBox.setStyleSheet("QFrame" 
                                        "{"
                                            "font-size: 24px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )
        self.request_statusBox.setGeometry(QRect(WINDOW_WIDTH-GIF_WIDTH-40, int(1.575*WINDOW_HEIGHT/2), 
                                            GIF_WIDTH, GIF_HEIGHT))

        self.request_statusText = QLabel("-----", self.request_statusBox)
        self.request_statusText.setAlignment(Qt.AlignCenter)
        self.request_statusText.setGeometry(QRect(0, 0, GIF_WIDTH, GIF_HEIGHT))

        self.loading = QLabel(self.centralwidget)
        self.loading.setStyleSheet('border: 1px solid black') # just for illustration
        self.loading.setGeometry(QRect(WINDOW_WIDTH-GIF_WIDTH-40, int(1.575*WINDOW_HEIGHT/2), 
                                    GIF_WIDTH, GIF_HEIGHT))
        # Loading the GIF
        self.movie = QMovie("loading.gif")
        self.movie.setScaledSize(QSize(GIF_WIDTH, GIF_HEIGHT))
        self.loading.setMovie(self.movie)
        self.stopAnimation()

        Window.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        self.retranslateUi(Window)
        QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Check Point"))
        self.Window_label.setText(_translate("Window", f'<html><head/><body><p align=\"center\"><span style=\" color:black;\">{self.gate_type} Carts Read</span></p></body></html>'))
        self.num_label.setText(_translate("Window", "#"))
        self.key_label.setText(_translate("Window", "Key"))
        self.logs_label.setText(_translate("MainWindow", "Logs"))
        self.logs_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

    def addRow(self, data):
        '''
        Add a row to Grid
        Args:
            data (dict): data to be added
        '''
        self.fetched_N = QLabel(str(self.row+1))
        self.fetched_N.setGeometry(QRect(0, 0, 80, 40))
        self.fetched_N.setStyleSheet("QFrame" 
                                        "{"
                                            "background-color: rgb(235,235,235);"
                                            "border-style: outset;"
                                            "border-width: 0.5px;"
                                            "border-radius: 4px;"
                                            "border-color: rgb(200,200,200);"
                                            "font-size: 24px;"
                                            "font-family: Times New Roman;"    
                                            "font-weight: bold;"
                                            "color: black;"
                                            "padding: 1px;"
                                        "}"
                                        )
        self.fetched_N.setAlignment(Qt.AlignCenter)
        self.fetched_N.setObjectName("fetched_#" + str(1+self.row))
        self.gridLayout.addWidget(self.fetched_N, self.row, 1, 1, 1)

        self.fetched_key = QLabel(str(data["key"]))
        self.fetched_key.setGeometry(QRect(0, 0, 80, 40))
        self.fetched_key.setStyleSheet("QFrame" 
                                            "{"
                                                "background-color: rgb(235,235,235);"
                                                "border-style: outset;"
                                                "border-width: 0.5px;"
                                                "border-radius: 4px;"
                                                "border-color: rgb(200,200,200);"
                                                "font-size: 24px;"
                                                "font-family: Times New Roman;"    
                                                "font-weight: bold;"
                                                "color: black;"
                                                "padding: 1px;"
                                            "}"
                                            )
        self.fetched_key.setAlignment(Qt.AlignCenter)
        self.fetched_key.setObjectName("fetched_key#" + str(1+self.row))
        self.gridLayout.addWidget(self.fetched_key, self.row, 2, 1, 7)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.row += 1
    
    def clearData(self):
        '''clear grid'''
        for i in reversed(range(self.gridLayout.count())): 
            self.gridLayout.itemAt(i).widget().setParent(None)
        self.row = 0

    def startAnimation(self):
        '''Start Buffering Animation'''
        self.loading.show()
        self.movie.start()
  
    def stopAnimation(self):
        '''Stop Buffering Animation'''
        self.movie.stop()
        self.loading.hide()

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = checkPoint_Window()
    ui.setupUi(MainWindow)
    json = [
            {
                "key":"151151",
            },
            {
                "key":"69669663",
            },
            {
                "key":"69669663",
            }
            ]
    for i in range(len(json)):
        ui.addRow(json[i])
    MainWindow.show()
    sys.exit(app.exec_())
